AWSTemplateFormatVersion: 2010-09-09
Description: Infrastructure for media counter application, []

Parameters:
  TableName:
    Type: String

Resources:
  DynamoDBTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "Id"
          AttributeType: "S"
        - 
          AttributeName: "Key"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "Id"
          KeyType: "HASH"
        - 
          AttributeName: "Key"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Ref TableName
      GlobalSecondaryIndexes: 
        - 
          IndexName: "IdHashKey"
          KeySchema: 
            - 
              AttributeName: "Id"
              KeyType: "HASH"
            - 
              AttributeName: "Key"
              KeyType: "RANGE"
          Projection: 
            NonKeyAttributes: 
              - "Key"
            ProjectionType: "INCLUDE"
          ProvisionedThroughput: 
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"

  